// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultimodalShippingSystem.Data;

#nullable disable

namespace MultimodalShippingSystem.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20260415082439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultimodalShippingSystem.Models.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipmentId");

                    b.ToTable("Shipments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MultimodalShippingSystem.Models.AirShipment", b =>
                {
                    b.HasBaseType("MultimodalShippingSystem.Models.Shipment");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isPriority")
                        .HasColumnType("bit");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("AirShipments", (string)null);
                });

            modelBuilder.Entity("MultimodalShippingSystem.Models.RoadShipment", b =>
                {
                    b.HasBaseType("MultimodalShippingSystem.Models.Shipment");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("RoadShipments", (string)null);
                });

            modelBuilder.Entity("MultimodalShippingSystem.Models.AirShipment", b =>
                {
                    b.HasOne("MultimodalShippingSystem.Models.Shipment", null)
                        .WithOne()
                        .HasForeignKey("MultimodalShippingSystem.Models.AirShipment", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MultimodalShippingSystem.Models.RoadShipment", b =>
                {
                    b.HasOne("MultimodalShippingSystem.Models.Shipment", null)
                        .WithOne()
                        .HasForeignKey("MultimodalShippingSystem.Models.RoadShipment", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
